{
 "title": "Hello",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Health",
   "type": "stat",
   "description": "Last health state of hello application",
   "gridPos": { "h": 8, "w": 5, "x": 1, "y": 0 },
   "targets": [
    { "expr": "hello_health" }
   ]
  },
  {
   "title": "hello_http_requests_total",
   "type": "graph",
   "description": "rate function example",
   "gridPos": { "h": 8, "w": 8, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum without (instance, job) (rate(hello_http_requests_total[5m]))"
    }
   ]
  },
  {
   "title": "Math.sin() function",
   "type": "graph",
   "description": "Sinus example for graph",
   "gridPos": { "h": 8, "w": 13, "x": 1, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "hello_sin " }
   ]
  }
 ]
}